### ISSUE TITLE
怎么才能手动安装

### ISSUE THREAD

**Issue by kkbbzjh** [0oVicero0/serverSpeeser_Install#10]
我下载了一个850M的完整版，想问一下，怎样才能手动安装那个centos7.1的serverspeeder_2727？已经生成了许可证了

**Comment by kkbbzjh** [comment]
在serverSpeeder kernel下载了apxfiles.tar.gz，然后在服务器解压了
接着把下载下来的serverspeeder_2727，改名为acce-3.10.61.12-[Centos_7.1_3.10.0-229.1.2.el7.x86_64]
接着放进/root/apxfiles/bin
然后，运行wget -O apx.lic http://serverspeeder.azurewebsites.net/lic?mac=$(ifconfig |grep -B1 "$(wget -qO- ipv4.icanhazip.com)" |awk '/HWaddr/{ print $5 }')生成了授权文件，并放进root/apxfiles/etc
然后在/root/apxfiles运行sh install.sh
会出现
cp: cannot stat `apxfiles/bin/*': No such file or directory
cp: cannot stat `apxfiles/etc/*': No such file or directory
chmod: cannot access `/serverspeeder/bin/*': No such file or directory
Installation done!
然后一直按回车，接着就出现
install.sh: line 172: /serverspeeder/bin/serverSpeeder.sh: No such file or directory
毫无疑问就失败了


请问一下是不是哪里做错了？

**Comment by 0oVicero0** [comment]
目录不正确，尝试 mkdir -p /serverspeeder/bin/
具体什么问题，我也不清楚。
你先研究一下他的各个安装文件再试一次。
实在不行的话，你用我给安装脚本，然后自己再换bin文件

**Comment by yfans** [comment]
apxfiles\etc\config 里面的配置改了没？ 
apxexe="/serverspeeder/bin/acce-3.10.61.12-[Centos_7.1_3.10.0-229.1.2.el7.x86_64]"
apxlic="/serverspeeder/etc/apx-20341231.lic"

**Comment by kkbbzjh** [comment]
#------------------------------------------------------#
#         do not change the following configs          #
#------------------------------------------------------#
usermode=0
licenseGen=0
checkLicense=0
accpath="/proc/net/appex"
apxlic="/serverspeeder/etc/apx-2035-12-31.lic"


这里提供的那个安装文件是上面那个样子的，没有：
apxexe="/serverspeeder/bin/acce-3.10.61.12-[Centos_7.1_3.10.0-229.1.2.el7.x86_64]"
这一项，要自己添加上去吗？

**Comment by kkbbzjh** [comment]
我加上了：apxexe="/serverspeeder/bin/acce-3.10.61.12-[CentOS_7.1_3.10.0-229.1.2.el7.x86_64]"
然后可以开始安装了，但是失败了，显示：
Failed to write configuration: /proc/net/appex/wanKbps

**Comment by 0oVicero0** [comment]
建议重启一下再试，这个错误如果不是内核问题就是内存不够。建议小内存的VPS不要用REHL/CentOS系列

**Comment by kkbbzjh** [comment]
好的，我试试，这个1G内存的啊。。。。应该够

**Comment by kkbbzjh** [comment]
重启了还是不行，我把内核也换了，换成一模一样的CentOS_7.1_3.10.0-229.1.2.el7.x86_64

**Comment by kkbbzjh** [comment]
我找到了一个别人的，但是要运行apx.php。有点麻烦，得装个lnmp，实在是不方便啊。
但是这个又运行不了，我谷歌了下，删除那个/serverspeeder/的文件夹，结果还是不行。。。。。

这个是我处理好的文件，能麻烦你帮忙看一下吗？谢谢！github上传不了，我就用网盘了。
https://mega.nz/#!SgZESSLL!IkNjYXWZ-1m_7Yv4fS8IFzMfrlHXYWHjLO6LHlm_Vqc
我把install.sh拉到root目录，然后bash install.sh运行，前面也没有提示任何问题，问题在最后，Failed to write configuration: /proc/net/appex/wanKbps，按照谷歌上的删除/serverspeeder/文件夹，并没有用。
