### ISSUE TITLE
The apx.iic fetching procedure is not correct

### ISSUE THREAD

**Issue by legendtang** [0oVicero0/serverSpeeser_Install#4]
lotServer checks `eth0`'s MAC address rather than your real interface's. Say you have two interface `eth0` and `eth1`. You want to accelerate `eth1` but you got `eth1`'s iic you cannot start lotServer.

**Comment by 0oVicero0** [comment]
Plase paste the result of `ifconfig` ,and mask your IP.

**Comment by legendtang** [comment]
@0oVicero0 
```
eth0      Link encap:Ethernet  HWaddr 00:16:3e:06:21:3d
          inet addr:***  Bcast:***  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:221 errors:0 dropped:0 overruns:0 frame:0
          TX packets:220 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:51486 (51.4 KB)  TX bytes:16521 (16.5 KB)

eth1      Link encap:Ethernet  HWaddr 00:16:3e:06:2b:dd
          inet addr:***  Bcast:***  Mask:255.255.252.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:41122 errors:0 dropped:0 overruns:0 frame:0
          TX packets:47281 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:14836589 (14.8 MB)  TX bytes:12502663 (12.5 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:916 errors:0 dropped:0 overruns:0 frame:0
          TX packets:916 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:103902 (103.9 KB)  TX bytes:103902 (103.9 KB)
```
The script uses `eth1` which is the interface connected to Internet to calculate the iic. I got a license error. Manually using `eth0` to get iic is okay. You should note that previously serverSpeeder did the same thing. You may also check https://github.com/91yun/serverspeeder

**Comment by 0oVicero0** [comment]
Show me the result `grep 'accif' /appex/etc/config`

**Comment by 0oVicero0** [comment]
I have changed the script, You can try it.

**Comment by legendtang** [comment]
@0oVicero0 The `accif` should be still `eth1`, the public Ethernet interface. I've tried your new script now it lets me input the public Ethernet interface manually. I've tried `eth1` but it still uses eth1 to calculate the MAC address, showing `not valid on current device`. You should make it to check `eth0` in the first place to calculate MAC address.

**Comment by 0oVicero0** [comment]
Now, It should work well.

**Comment by legendtang** [comment]
This time your script is perfectly working. Thank you!
