### ISSUE TITLE
一键安装后加速模块如何更换

### ISSUE THREAD

**Issue by haruhitamako** [0oVicero0/serverSpeeser_Install#9]
Debian_7_3.2.0-4-amd64默认安装3.9.10.41加速模块，如何更换为受支持的3.10.61.0模块

**Comment by 0oVicero0** [comment]
直接下载之后，重新命名就可以了。

**Comment by haruhitamako** [comment]
模块已经下载到本地改名为acce-3.10.61.0-[Debian_7_3.2.0-4-amd64]了，放到哪个目录下？

**Comment by 0oVicero0** [comment]
/appex/bin

**Comment by haruhitamako** [comment]
感谢
